# Generated by Django 5.0.6 on 2024-07-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logup', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
