# Generated by Django 5.0.6 on 2024-07-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logup', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=45)),
                ('category_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_title', models.CharField(max_length=45)),
                ('job_type_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=45)),
                ('skill_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_member',
            new_name='is_dealer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username1',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DealerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, default='dealer/company/logos/default_profile.png', upload_to='dealer/company/logos')),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('company_short_desc', models.CharField(max_length=100)),
                ('company_desc', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_desc', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('github_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='costomer/images/profile_pic/default_profile_Is8arW2.png', upload_to='costomer/images/profile_pic')),
                ('resume', models.FileField(blank=True, upload_to='costomer/files/resumes')),
                ('long_description', models.TextField(null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('available', models.CharField(blank=True, max_length=255, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logup.jobcategorymodel')),
                ('skills', models.ManyToManyField(blank=True, to='logup.skillmodel')),
            ],
        ),
    ]
